version: '3.4'

services:
  mongodb:
    image: mongo
    container_name: hobbies_mongodb
    restart: always
    ports:
      - 37017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - app-network

  user-hobbies:
    build: .
    container_name: user_hobbies
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    networks:
      - app-network
    ports:
      - '3000:3000'
    depends_on:
      - mongodb

networks:
  app-network:
    driver: bridge
